name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build project
      run: |
        npm ci
        npm run build
      env:
        CI: true

    - name: Publish to NPM registry
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
